export const brandsData = [
  {
    "id":1,
    "attributes":{
        "name":"ebay",
        "logo":{
          "data":{
              "id":8,
              "attributes":{
                "width":400,
                "height":160,
                "formats":{
                    "thumbnail":{
                      "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/thumbnail_E_Bay_logo_2x_abef51fd7d.png",
                      "width":245,
                      "height":98
                    }
                },
                "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/E_Bay_logo_2x_abef51fd7d.png",
              }
          }
        }
    }
  },
  {
    "id":2,
    "attributes":{
        "name":"ebay",
        "logo":{
          "data":{
              "id":8,
              "attributes":{
                "width":400,
                "height":160,
                "formats":{
                    "thumbnail":{
                      "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/thumbnail_E_Bay_logo_2x_abef51fd7d.png",
                      "width":245,
                      "height":98
                    }
                },
                "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/E_Bay_logo_2x_abef51fd7d.png",
              }
          }
        }
    }
  },
  {
    "id":3,
    "attributes":{
        "name":"ebay",
        "logo":{
          "data":{
              "id":8,
              "attributes":{
                "width":400,
                "height":160,
                "formats":{
                    "thumbnail":{
                      "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/thumbnail_E_Bay_logo_2x_abef51fd7d.png",
                      "width":245,
                      "height":98
                    }
                },
                "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/E_Bay_logo_2x_abef51fd7d.png",
              }
          }
        }
    }
  },
  {
    "id":4,
    "attributes":{
        "name":"ebay",
        "logo":{
          "data":{
              "id":8,
              "attributes":{
                "width":400,
                "height":160,
                "formats":{
                    "thumbnail":{
                      "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/thumbnail_E_Bay_logo_2x_abef51fd7d.png",
                      "width":245,
                      "height":98
                    }
                },
                "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/E_Bay_logo_2x_abef51fd7d.png",
              }
          }
        }
    }
  },
  {
    "id":5,
    "attributes":{
        "name":"ebay",
        "logo":{
          "data":{
              "id":8,
              "attributes":{
                "width":400,
                "height":160,
                "formats":{
                    "thumbnail":{
                      "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/thumbnail_E_Bay_logo_2x_abef51fd7d.png",
                      "width":245,
                      "height":98
                    }
                },
                "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/E_Bay_logo_2x_abef51fd7d.png",
              }
          }
        }
    }
  },
  {
    "id":6,
    "attributes":{
        "name":"ebay",
        "logo":{
          "data":{
              "id":8,
              "attributes":{
                "width":400,
                "height":160,
                "formats":{
                    "thumbnail":{
                      "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/thumbnail_E_Bay_logo_2x_abef51fd7d.png",
                      "width":245,
                      "height":98
                    }
                },
                "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/E_Bay_logo_2x_abef51fd7d.png",
              }
          }
        }
    }
  },
]

export const headlinesData = [
  {
    "id":1,
    "attributes":{
        "name":"Adweek",
        "quote":"\"Kyra aims to bring more performance based models to TikTok's creators\"",
        "logo":{
          "data":{
              "id":18,
              "attributes":{
                "width":2880,
                "height":1036,
                "formats":{
                  "thumbnail":{
                    "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/thumbnail_Adweek_logo_svg_9f3709bc40.png",
                    "width":245,
                    "height":88
                  }
                },
                "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/Adweek_logo_svg_9f3709bc40.png",
              }
          }
        }
    }
  },
  {
    "id":2,
    "attributes":{
        "name":"Adweek",
        "quote":"\"Kyra aims to bring more performance based models to TikTok's creators\"",
        "logo":{
          "data":{
              "id":18,
              "attributes":{
                "width":2880,
                "height":1036,
                "formats":{
                  "thumbnail":{
                    "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/thumbnail_Adweek_logo_svg_9f3709bc40.png",
                    "width":245,
                    "height":88
                  }
                },
                "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/Adweek_logo_svg_9f3709bc40.png",
              }
          }
        }
    }
  },
  {
    "id":3,
    "attributes":{
        "name":"Adweek",
        "quote":"\"Kyra aims to bring more performance based models to TikTok's creators\"",
        "logo":{
          "data":{
              "id":18,
              "attributes":{
                "width":2880,
                "height":1036,
                "formats":{
                  "thumbnail":{
                    "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/thumbnail_Adweek_logo_svg_9f3709bc40.png",
                    "width":245,
                    "height":88
                  }
                },
                "url":"https://strapi-new-s3.s3.eu-west-1.amazonaws.com/Adweek_logo_svg_9f3709bc40.png",
              }
          }
        }
    }
  },
]